format = """
[](fg:sky bg:none)[  ](bg:sky fg:base)[](fg:sky bg:none)\
$conda\
$docker_context\
$directory\
$git_branch\
$git_status\
$fill\
$python$nodejs$java$golang\
$line_break\
$character
"""
 
add_newline = false
palette = 'catppuccin_mocha'
 
[directory]
style = "bg:sapphire fg:base"
format = "[ $path [](bg:none fg:sapphire)]($style)"
truncation_length = 1
truncation_symbol = "…/"
 
# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "
 
[fill]
symbol = " "
 
[conda]
symbol = " "
style = "bg:lavender fg:base"
format = '[ $symbol $environment ]($style)[](fg:lavender bg:none)'
 
[docker_context]
symbol = " "
style = "bg:lavender fg:base"
format = '[ $symbol $context ]($style)[](fg:lavender bg:none)'
 
[git_branch]
symbol = ""
style = "bg:teal fg:base"
format = '[ $symbol $branch ]($style)'
 
[git_status]
style = "bg:teal fg:base"
format = '[$all_status$ahead_behind [](fg:teal bg:none)]($style)'
 
[python]
symbol = ""
style = "bg:blue fg:base"
format = '[[](fg:blue bg:none) $symbol $version [](fg:blue bg:none)]($style)'
 
[golang]
symbol = ""
style = "bg:blue fg:base"
format = '[[](fg:blue bg:none) $symbol $version [](fg:blue bg:none)]($style)'
 
[nodejs]
symbol = ""
style = "bg:blue fg:base"
format = '[[](fg:blue bg:none) $symbol $version [](fg:blue bg:none)]($style)'
 
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

